apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3 #as asked in the assignment
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.20.2
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html #this is needed to return random text from the nginx server
              name: nginx-config
              subPath: index.html
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 250m
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: index.html
                path: index.html
